import { GoogleGenAI, Modality } from "@google/genai";

const parseDataUrl = (dataUrl: string) => {
  const match = dataUrl.match(/^data:(.+);base64,(.+)$/);
  if (!match) {
    throw new Error("Invalid data URL");
  }
  return { mimeType: match[1], data: match[2] };
};

export interface ModelAssets {
    face?: string;      // base64 data URL
    outfit?: string;    // base64 data URL
    background?: string;// base64 data URL
}

export const generateModel = async (
  assets: ModelAssets,
  userPrompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const parts: any[] = [];

  // Construct a detailed prompt for the model
  let modelPrompt = `Create a realistic, full-body vertical portrait of a model.
  - The model's pose should be natural and stylish.
  - The final image aspect ratio must be vertical (e.g., 3:4 or 9:16).
  `;

  if (assets.face) {
    modelPrompt += "- Use the provided face for the model.\n";
    const { mimeType, data } = parseDataUrl(assets.face);
    parts.push({ inlineData: { mimeType, data } });
  }
  if (assets.outfit) {
    modelPrompt += "- The model should be wearing the provided outfit.\n";
    const { mimeType, data } = parseDataUrl(assets.outfit);
    parts.push({ inlineData: { mimeType, data } });
  }
  if (assets.background) {
    modelPrompt += "- Place the model in the provided background environment.\n";
    const { mimeType, data } = parseDataUrl(assets.background);
    parts.push({ inlineData: { mimeType, data } });
  }

  modelPrompt += `- Additional instructions: ${userPrompt}`;
  parts.unshift({ text: modelPrompt }); // Add text prompt at the beginning

  if (parts.length <= 1) {
    throw new Error("At least one asset (face, outfit, or background) must be provided.");
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const newBase64Data = part.inlineData.data;
      const newMimeType = part.inlineData.mimeType;
      return `data:${newMimeType};base64,${newBase64Data}`;
    }
  }

  throw new Error("No image was generated by the API.");
};


export const editImage = async (
  base64ImageDataUrl: string,
  prompt: string,
  assets?: ModelAssets
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
  }

  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const parts: any[] = [];

  // Base image to be edited is always the first part.
  const { mimeType, data } = parseDataUrl(base64ImageDataUrl);
  parts.push({ inlineData: { mimeType, data } });

  let finalPrompt = prompt;

  if (assets && Object.keys(assets).length > 0) {
    let advancedPrompt = `You are an expert photo editor. Edit the first image based on the following instructions and subsequent reference images.`;
    
    if (assets.face) {
        advancedPrompt += "\n- A reference face is provided. Replace the face in the first image with this one.";
        const { mimeType, data } = parseDataUrl(assets.face);
        parts.push({ inlineData: { mimeType, data } });
    }
    // 'outfit' is used as a general 'reference' image for style/content
    if (assets.outfit) {
        advancedPrompt += "\n- A reference image is provided. Use it for style, content, or other inspiration.";
        const { mimeType, data } = parseDataUrl(assets.outfit);
        parts.push({ inlineData: { mimeType, data } });
    }
    if (assets.background) {
        advancedPrompt += "\n- A reference background is provided. Replace the background in the first image with this one.";
        const { mimeType, data } = parseDataUrl(assets.background);
        parts.push({ inlineData: { mimeType, data } });
    }
    
    if (prompt) {
        advancedPrompt += `\n- Additional user instructions: "${prompt}"`;
    } else {
        advancedPrompt += `\n- Perform the edits as described using the reference images precisely and without other changes.`;
    }
    finalPrompt = advancedPrompt;
  }
  
  parts.push({ text: finalPrompt });

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const newBase64Data = part.inlineData.data;
      const newMimeType = part.inlineData.mimeType;
      return `data:${newMimeType};base64,${newBase64Data}`;
    }
  }

  throw new Error("No image was generated by the API.");
};